[package]
name = "gallery"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
csv = "1.3.0"
regex-lite = "0.1.5"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
ureq = { version = "2.9.7" }
